### ISSUE TITLE
Resize font parameter

### ISSUE THREAD

**Issue by LucasPMarcelino** [Blazored/Toast#199]
**Is your feature request related to a problem? Please describe.**
I want to choose the size of texts in Toast

**Describe the solution you'd like**
Could be a parameter for each text and we choose a simple size like CSS, for example: 12px, 10px...

**Describe alternatives you've considered**
Simple parameter

**Additional context**
We like to use Blazored Toasts and we want to improve our website with this new tools

**Comment by chrissainty** [comment]
Hi @LucasPMarcelino,

This isn't something I can see me adding. In order to do this I'd have to apply inline styles which I prefer to stay away from whenever possible. This is also pretty easy to achieve yourself. You can either override `.blazored-toast .blazored-toast-message` and apply your desired font size there. Or you can use the custom component option and have complete control over how your toasts look.
