### ISSUE TITLE
[Question] No styles

### ISSUE THREAD

**Issue by adria-arquimbau** [Blazored/Toast#219]
**Please be sure to check the readme file before raising an issue.**

Hi!

Seems like I made all the steps regarding configuration and the styles doesn't load correctly.

![image](https://github.com/Blazored/Toast/assets/59824832/d76f0878-de91-476d-b1e0-6216c39aa833)

here is my index.html file:

`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>EventsManager</title>
    <base href="/" />
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="css/app.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />
    <link href="XXXX.Client.styles.css" rel="stylesheet" />
</head>

<body>
<div id="app">
    <svg class="loading-progress">
        <circle r="40%" cx="50%" cy="50%" />
        <circle r="40%" cx="50%" cy="50%" />
    </svg>
    <div class="loading-progress-text"></div>
</div>

<div id="blazor-error-ui">
    An unhandled error has occurred.
    <a href="" class="reload">Reload</a>
    <a class="dismiss">🗙</a>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
<script src="_framework/blazor.webassembly.js"></script>
<script>navigator.serviceWorker.register('service-worker.js');</script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@fluentui/web-components@2.0.2/dist/web-components.min.js"></script>
</body>

</html>`

Regular styles in the application work correctly.

All steps regarding config, `builder.Services.AddBlazoredToast();` imports: `@using Blazored.Toast
@using Blazored.Toast.Services`

And MainLayout:
`<div class="page">
    <div class="sidebar">
        <NavMenu />
    </div>

    <main>
        <div class="top-row px-4 auth">
            <LoginDisplay />
            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
        </div>

        <article class="content px-4">
            @Body
        </article>
    </main>
</div>

<BlazoredToasts Timeout="3" ShowCloseButton="false" ShowProgressBar="true" Position="ToastPosition.TopRight" RemoveToastsOnNavigation="true" />`

Maybe a conflict within the index.html file?

Thanks

**Comment by taylorchasewhite** [comment]
This is almost certainly going to be tied to the CSS bundling. There's a note about this in the description, [here](https://github.com/Blazored/Toast#3-add-reference-to-style-sheets). Looks like your index.html file is missing the `<link/>` element that is including your bundled styles.

There's a more detailed description on bundling from Microsoft, [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0#css-isolation-bundling).

Also, note that if you're including the BlazoredToasts in a razor class library _of your own_ (i.e. a component project that's not your _main_ Client csproj project, you need to have at least one component that has an isolated css file associated with it in order to trigger bundling (i.e. MyComponent.razor.css) to include the BlazoredToast stylesheet in the bundled stylesheet of your _own_ RCL.
