### ISSUE TITLE
New override to InMemoryToastService to include toast details

### ISSUE THREAD

**Issue by jennifer-lebantino** [Blazored/Toast#228]
**Is your feature request related to a problem? Please describe.**
When testing custom toast components that use BlazoredToast, not enough information is passed to the InMemoryToastService. This limits test capability as there's not enough detail available (i.e. toast level, message).

**Describe the solution you'd like**
It would be great to add an override that takes in whole components in the InMemoryToastService so we can access this data.

**Describe alternatives you've considered**
Currently I can only test that some toast message does appear which defaults to an 'info' level and the message is null.

**Additional context**
N/A

**Comment by TheoWakelin** [comment]
Instead of adding a new override that takes in whole components to the InMemoryToastService, a nullable ToastParameters field could be added to the InMemoryToast class, which is then populated when ToastParameters is passed as a parameter to the ShowToast<TComponent> overrides. 

If this approach is okay, I can get a PR created for this.
