### ISSUE TITLE
Replace Toast Level CssClasses rather than adding AdditionalClasses

### ISSUE THREAD

**Issue by taylorchasewhite** [Blazored/Toast#44]
Right now in the BlazoredToasts component there are a number of parameters that users can set including a class to apply styles to each of the different toast levels:

- ErrorClass
- InfoClass
- SuccessClass
- WarningClass

Right now these parameters set additional classes on each of the toast instances, but they don't remove the default styling.

This means that a consumer needs to find out the base css class of each warning and create selectors more specific than those classes.

Could we change this so that setting the above parameters replaces the default styles rather than adds CSS classes in addition to? 

One example use case would be styling the cards using Boostrap (or a similar CSS framework) by applying various [alert classes](https://getbootstrap.com/docs/4.0/components/alerts/) to the toast instance.

Note that changing this to be a "replace" rather than "in addition to" would be a breaking change for folks that implemented their CSS with the assumption of the blazor-toast-warning/blazor-toast-error etc..

**Comment by chrissainty** [comment]
I think this issue is a tricky one. While what you've said would be helpful from the point of view of someone who wants to remove all default styling and replace it entirely, it makes life much harder for someone who only wants to override a single value or a couple of values. 

The pattern of adding additional classes which override existing ones is pretty common in UI libraries as it's trivial to understand the base styles which are being applied and select which ones to override. 

Based on what I've said above and the fact this would be a breaking change to existing users who rely on the current functionality, I don't think this is a change that I would want to make right now.
